import { NavLink } from 'react-router-dom'
import { Button } from '../../../../components/ui/button'
import { Binary } from 'lucide-react'

const WelcomeMessage = () => {
  return (
    <div className='w-full flex justify-center items-center flex-col p-16 md:p-24 gap-5'>
      <div className="text-center">
      <h1 className=' text-4xl font-bold '><Binary className="inline text-lime-500" /> Welcome <Binary className="inline text-lime-500" /></h1>
        <p className='text-2xl'>To start Check out the tool box up top, select the language and the topic.</p>
      </div>
      <div className="">
        <p className='text-lg p-1'><span className='font-bold underline'>Most Viewed Button</span> : analyze the top 20 youtube videos based on the given topic and then generate 20 titles similer to those titles.</p>
        <p className='text-lg p-1'><span className='font-bold underline'>Ai Button</span> : 20 titles generated by ChatGPT base on the given topic.</p>
      </div>
      <div className="">
        <NavLink to={"../../contact"}>
          <Button>Contact Us</Button>
        </NavLink>
        <p className='text-lg inline ms-2'>for any help you can contact us any time.</p>

      </div>
    </div>
  )
}

export default WelcomeMessage